[package]
name = "dagster_pipes_rust"
version = "0.1.2"
edition = "2021"
description = "A Dagster pipes implementation for interfacing with Rust"
license = "Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0"
flate2 = "1"
