name: build-and-release-dagster-qdrant

on:
  push:
    tags:
      - 'dagster_qdrant-*.*.*'

jobs:
  build-and-release-dagster-qdrant:
    uses: ./.github/workflows/template-release.yml
    with:
      library_name: dagster-qdrant
      working_directory: ./libraries/dagster-qdrant
    secrets: inherit
